# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('youtube_urls', models.CharField(max_length=100)),
                ('youtube_views', models.IntegerField()),
                ('youtube_likes', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
