# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='youtube_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video.Category'),
            preserve_default=False,
        ),
    ]
