# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symmetrical.Vehicle')),
            ],
            bases=('symmetrical.vehicle',),
        ),
        migrations.CreateModel(
            name='Buss',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symmetrical.Vehicle')),
                ('num_passengers', models.IntegerField()),
            ],
            bases=('symmetrical.vehicle',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symmetrical.Vehicle')),
                ('type', models.CharField(max_length=100)),
            ],
            bases=('symmetrical.vehicle',),
        ),
    ]
