# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symmetrical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
