# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person2', '0002_auto_20161007_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge')], max_length=1),
        ),
    ]
