# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person2', '0006_auto_20161010_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
